### ISSUE TITLE
Use UMD for npm package

### ISSUE THREAD

**Issue by erquhart** [layerhq/layer-websdk#144]
A lot of folks are using npm as a package manager for the web. Have you considered using UMD?

**Comment by michaelkantor** [comment]
According to https://github.com/substack/node-browserify#usage
The `--standalone` flag generates a UMD build.

Our build script uses this flag:

https://github.com/layerhq/layer-websdk/blob/master/Gruntfile.js#L182

So, since we don't use UMD ourselves, I'd like to pass it back to you to take a closer look and see if this is not generating what its supposed to.  If you clone this repo, you can tweak the parameters and see if you get a better result.

Michael

**Comment by erquhart** [comment]
Fair enough! Thanks.
