### ISSUE TITLE
Safari issue

### ISSUE THREAD

**Issue by jeffijoe** [layerhq/layer-websdk#147]
This is what I see in staging:

![image](https://cloud.githubusercontent.com/assets/2505474/24874307/7c4ba4e0-1e24-11e7-9fd5-ce0e9c5de535.png)

This has been going on for a while. In production (in all browsers) I see:

![image](https://cloud.githubusercontent.com/assets/2505474/24874385/b8f9a716-1e24-11e7-968e-5c5db14c11f9.png)

Even though in non-Safari browsers everything still works.

We use Auth0 Delegation Tokens.

**Comment by michaelkantor** [comment]
Is this still happening?

If you have a curl request with a session token that continues to recreate this issue; you can email it to me.  Before sending this however, you need to make sure that your staging Session ID won't expire before I can try it and have server engineers try it.  

you can set how long your session tokens last using the Server API operation https://docs.layer.com/reference/server_api/users.out#set-session-ttl

**Comment by jeffijoe** [comment]
Thats the thing, doing a curl request works fine, Chrome works fine, but in Safari it fails due to a CORS issue in staging. In production it seems to work fine for me but one of our customers is reporting an issue in Safari and it works for them in Chrome too, although there seems to be no CORS issue there.

![image](https://cloud.githubusercontent.com/assets/2505474/24947105/b91a8174-1f65-11e7-8d34-086f79df5d1c.png)

**Comment by michaelkantor** [comment]
Obviously something out of the ordinary is happening here.  It works for your users in most browsers... it works for our other users in all browsers.  My best guess is that there's something going on in the environment.

Best I can do is to suggest you post the preflight request/response (I suspect thats whats shown a few rows above the request selected in your picture above.  Make sure that ALL response and request headers are visible in your Preflight picture.

**Comment by jeffijoe** [comment]
That's the weird part. Here's one of them:

![image](https://cloud.githubusercontent.com/assets/2505474/25003788/6c0cf460-2051-11e7-9486-96e35f16135c.png)

It's a `GET` request and not an `OPTIONS` request, I don't see any `OPTIONS` request to Layer at all in Safari.

**Comment by michaelkantor** [comment]
My tests in Safari 10.1 are showing the same headers, but no error.  What version of safari are you in?

**Comment by jeffijoe** [comment]
Safari 10.

On 14 Apr 2017, at 23.40, Michael Kantor <notifications@github.com<mailto:notifications@github.com>> wrote:


My tests in Safari 10.1 are showing the same headers, but no error. What version of safari are you in?

**Comment by michaelkantor** [comment]
I just ran a test in 10.0, still works for me.  Send me a URL/credentials, and I'll see if your app behaves any different for me.

**Comment by jeffijoe** [comment]
I think 10.0, not at my mac right now. I can only repro in staging.

On 14 Apr 2017, at 23.40, Michael Kantor <notifications@github.com<mailto:notifications@github.com>> wrote:


My tests in Safari 10.1 are showing the same headers, but no error. What version of safari are you in?

**Comment by jeffijoe** [comment]
https://app.t4xstokers.com

Email: jobsapi@test.com
Password: 123456

**Comment by michaelkantor** [comment]
Ok, was unable to replicate this on safari in my laptop.

However, I was able to replicate this in safari running in Saucelabs.

Here's my best guess:  Safari, if run on a Really good network, is able to fire off requests fast enough to get rate limited.  Rate limiting errors lack proper CORS headers.  I've filed a ticket to the server team to fix this.

I can't estimate when that will get handled.  I can say that your firing an awful lot of "GET /conversations/UUID/messages" requests.  And your pagination_window of 100 means your sucking down a LOT of data.  The fastest fix to the problem above is to adjust your technique a little.  And you will benefit in other ways by changing your technique a little. Feel free to follow up here or elsewhere with what your trying to accomplish with all of those requests if you want to brain storm on alternate approaches.

That doesn't change the fact that our server team must fix this; the fact that developers can't even see that they are rate limited is terrible.

**Comment by jeffijoe** [comment]
I was using Safari on macOS and it had the same issue on iOS.

This was just a small sample, in prod we fire off a lot more. Each job has a conversation, and I fetch messages early to display unread counts.

**Comment by michaelkantor** [comment]
Are you trying to get:

* A single unread count summed across all Conversations?
* A separate unread count for each Conversation?

We recommend the following for tackling either problem above:

* Each conversation has an `conversation.unreadCount` property that tells you how many unread Messages there are.  This means if you get a list of Conversations, you can iterate over them to get the answers you need.
* Due to a server-side bug we are currently working on where it can be problematic to clear `unreadCount`, we actually recommend just doing `conversation.lastMessage && conversation.lastMessage.isRead ? 0: 1` to get whether a Conversation has unread messages or not.
* At no point is it needed to fetch huge numbers of messages in order to calculate this yourself
* Prefetching thousands of messages only 20 of which the user is currently able to see is both adding drag to your client and its network, and being somewhat aggressive in how you use our services.  I strongly recommend against this.

**Comment by jeffijoe** [comment]
I never fetch the convo itself, just the messages. Our own data has a convo id.

I want to show an unread count per convo.

**Comment by michaelkantor** [comment]
Ok.  That makes sense.  Here's what I suggest so that you don't have to fetch thousands of messages:

1. Use a Conversation Query to get the first 100 Conversations. In most cases that will get all the conversations that matter, and you'll get each Conversation's `unreadCount` (or as I suggested `lastMessage.isRead`)
2. For any Conversation that you failed to fetch, you can load individual Conversations instead of ALL messages of all Conversations; use `getConversation` as documented here: https://docs.layer.com/api_reference/web-3.0/#!/api/layer.mixins.ClientConversations-method-getConversation     You can determine if a given Conversation was fetched by the query by simply doing `client.getConversation(convId)` or alternatively doing `client.getConversation(convId, true)` to get it from client cache or from the server if not cached.

The above pattern should simplify things a little. This may still get rate limited if you have massive numbers of Conversations.  But you shouldn't be doing this on massive numbers of Conversations.  You should instead:

1. Render a page of Conversations, and only get unread counts for that page
2. When the user scrolls to the next page, fetch unread counts for the next page

Prefetching absolutely everything is not scalable.  Your getting rate limited.  Our server team can fix things so that you KNOW when your being rate limited.  But any strategy you apply to your application that gets you rate limited should be presumed to be a strategy that needs to be refined.

The only reason Chrome and other browsers aren't rate limiting you is that they allow for a smaller number of simultaneous connections, slowing down the number of requests that go out.  So instead of getting rate limited, you get crappy load time.  Not sure which is preferred :-)

**Comment by jeffijoe** [comment]
I honestly doubt it was rate-limiting. I've had the same issue with just 1 conversation.

**Comment by michaelkantor** [comment]
Its frustrating that I can only replicate this issue in safari on saucelabs and that among other things, this means I can't even see the error status code, nor setup any side mechanisms for listening to network traffic.  I believe it to be rate limiting errors due to the fact that I see a lot of successful requests, followed by a series of CORS errors.

If you can setup an example with 1 conversations, I'd like to see it and figure out what is going on.

**Comment by jeffijoe** [comment]
Sure thing, tomorrow I will clear our staging env and set up just 1 job, same account.

If I know the demogods, it works fine with 1 convo tomorrow lol

**Comment by jeffijoe** [comment]
Yeah it works with one convo, classic lol.

What exactly are you rate-limiting on? The amount of messages being pulled within a certain interval, or amount of requests?

**Comment by michaelkantor** [comment]
Number of requests per second.  Safari on a very good network seems able to achieve what other browsers cannot.

**Comment by michaelkantor** [comment]
We have deployed updates to our rate limits.  I can't gaurentee that you won't be rate limited still, but I think it unlikely, unless your querying for messages across a lot of Conversations.

**Comment by jeffijoe** [comment]
Thanks!
