### ISSUE TITLE
Wrong Read Status

### ISSUE THREAD

**Issue by grimabe** [layerhq/layer-websdk#30]
Hi,
I am using http://cdn.layer.com/sdk/0.9/layer-websdk.min.js url for the web sdk.
I was using the **0.9.1** and I guess due to the **0.9.2** or **0.9.3** version the read status of messages are not working anymore.

I am setting the isRead message property to true and I am sure it is working because on the mobile application with the iOS SDK the status is **read**.

But when I query the list of conversations through the web sdk for example and I look at the **isRead** property of the **lastMessage** property of the conversation the value is **false**

I attached a screenshot of the message object :
![screen shot 2016-03-29 at 12 49 34](https://cloud.githubusercontent.com/assets/1334148/14105619/0f6c081a-f5ad-11e5-8a62-6a5da84291c2.png)

Thank you for helping me resolving this.

**Comment by michaelkantor** [comment]
isRead does not show up in your picture; this is probably because properties controlled via propertySetters/getters don't tend to render well.  Still, its absence confuses the above picture.  Whats worse, __isRead, the internal version of the property also does not show up. Other internal properties (__parts, __recipientStatus) do show up.  There are very few paths where that property would be left unset, and none of them would give you a __recipientStatus that was as clearly populated as yours.  This failure to set the property entirely is likely tied to our problem.

Can you replicate this error?

- If you can replicate the error, can you send us steps we can follow to replicate the error?
- If can you replicate this error, do so with the debugger open and break-on-error enabled (break on all errors, not just uncaught errors). 
    - Do you see any errors thrown that might prevent the object from being correctly setup?  
    - If so, please run with http://cdn.layer.com/sdk/0.9/layer-websdk.js, and send us line numbers, stack traces, screen shots of the debugger, etc... where the error occurs.

**Comment by michaelkantor** [comment]
Closing this due to 28 days inactivity.  Can discuss further if new information becomes available.
