### ISSUE TITLE
Two client's instaces

### ISSUE THREAD

**Issue by alanhoff** [layerhq/layer-websdk#48]
Hello folks,

Is it possible to instantiate two `layer.Client` in the same browser? I don't think so because the `ready` event is never fired for the second client.

Appreciate any advice.

**Comment by michaelkantor** [comment]
You can instantiate two clients, but only if they have different App IDs.  You can not instantiate two clients pointing to the same App ID, but using a different UserID.

This is a limitation that can be lifted, but would require discussion and use cases.

**Comment by alanhoff** [comment]
@michaelkantor in our scenario we're using Layer as a concierge application, so we have sever users asking for help/questions and several admins to help/answer them.

The solution we found was to implement the following architecture:

* Each app's user have one Layer user and one conversation
* Each admin have one Layer user
* We also have one "global user" that is attached to every created conversation

The global user is used only by the admins to:

* List all conversations
* Show conversations with pending questions
* Join, assign and leave an admin
* Notify when new message arrive

The main problem here is that we had to choose between having a WebSDK instance for the admin or for global user. We opted for assigning the WebSDK instance to the global user because it do the most part of the work, then for the admin we're using a HTTP Client for sending messages.

Do you have any suggestions, or do you think that this is a valid scenario for lifting this limitation?

**Comment by michaelkantor** [comment]
1. let me point out that this limitation is front and center in our minds, and we are hard at work coming up with a solution to this throughout our services that does not require use of dual logins for all admins.  And if I could tell you WHEN that would become available, I would... I note this simply to say that you should focus on getting this working, and prepare to redo a little work in the future to get a better result.
2. Some of our customers are trying solutions that use Platform API instead of multiple clients.  The Platform API lets the browser send a request to your server, and your server requests Conversations or joins/leaves the Conversation on your user's behalf.  This gets around needing an "Admin" user that is part of every Conversation.
3. Platform API can actually manage this better than the Client API in that it will deliver data to your server, and your server can filter it and distribute it to all of your admins.

One other type of solution you might look at:  Lets say you've got two tabs, one for your "Admin" UI and one for your "Agent" UI.  You can put everything in the "Admin" UI in an iframe, which would allow it to have a separate Client from the Client on the main window.

**Comment by alanhoff** [comment]
@michaelkantor thanks for the quick reply. Your iframe ideia sounds like a good short-term solution. I'll close this issue and will keep an eye for updates.

**Comment by michaelkantor** [comment]
I've just been reminded @alanhoff that the "admin" user will not scale well as it accumulates large numbers of Conversations.  Any user that is a part of ALL Conversations:
1. Will be disabled once it hits 30,000 Conversations
2. May experience performance problems as it becomes large

If your working on a prototype or proof of concept app, then these things probably won't affect you.  But if you want to have something that will scale reasonably without being rushed to update things at some point, a solution that uses the Platform API bypasses the need for a special "admin" user.
