### ISSUE TITLE
Integrating layer-WebSDK in Cordova applications

### ISSUE THREAD

**Issue by allen8300** [layerhq/layer-websdk#75]
Hi, I tried all three ways there: NPM, CDN, Source;

But I still cannot call layer.Client successfully in my ionic app.

Please give some advice

**Comment by michaelkantor** [comment]
This is not yet reviewed and released, but you can see some examples of how we got our sample app to work in Cordova at:
https://github.com/layerhq/layer-js-sampleapps/tree/cordova/phonegap

PS: You would NOT want to use CDN; optimal is to load it from your device so that it can initialize while offline.

If you have any further comments on this topic, please comment in the layer-js-sampleapps repo.

Michael
